Apply pop up on view project description button
byiringiroscar/portfolio_desktop_microverse.github.io pull request #8
Opened 2023-02-08 18:26 UTC by byiringiroscar

<h3>Pop on view project</h3>

- Apply pop up on view project description button
- Apply responsiveness in mobile version

2023-02-08 19:00 UTC, MeqdamAlqudah requested changes
Hi @byiringiroscar , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet.

![image](https://user-images.githubusercontent.com/74744787/217626452-5182bc2f-4e50-4038-b47a-68a88387d6d6.png)

 ## Highlights
:+1: no linter errors 
:+1: Javascript

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-08 19:00 UTC, MeqdamAlqudah commented on index.html
>                      <li><a href="#" class="project-tag-a">Ruby</a></li>
- [x] Please the overlay color should be blur as in the design 

|Yours | Figmas |
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/74744787/217624472-43aed950-63c4-4b2b-b01c-7439923f8a14.png)  | ![image](https://user-images.githubusercontent.com/74744787/217624587-0374ab79-a26f-40d8-88eb-40543e36b4ed.png)  |

2023-02-08 19:00 UTC, MeqdamAlqudah commented on index.html
- [x] Please the popup should be responsive look how it look in mobile size , the length of this popup is not responsive 
![image](https://user-images.githubusercontent.com/74744787/217625351-ba317f03-d1c6-4d95-b973-a0aaeebd2985.png)

2023-02-08 19:00 UTC, MeqdamAlqudah commented on index.html
> +                    <a href="#" id="view-project-id" class="modal-link">See Project</a>
- [x] Please fix the MIT link in the Readme file it is broken 
![image](https://user-images.githubusercontent.com/74744787/217625793-424b0071-8b17-4b15-a6ba-c1295bf85ba0.png)
![image](https://user-images.githubusercontent.com/74744787/217625971-88b62c5a-a447-4b33-a863-44682d27450f.png)

2023-02-08 21:16 UTC, cynthiainga requested changes
Hi @byiringiroscar, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet.

![](https://user-images.githubusercontent.com/80612925/157397398-00904e26-60ec-46cd-9510-240661c250ef.gif)

 ## Highlights

- [ ] No linters errors ✔️ 
- [ ] Descriptive PR ✔️ 
- [ ] Correct Github flow ✔️ 

 ## Required Changes ♻️

- [ ] Please kindly check the comment under the review 👇 👇 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-08 21:16 UTC, cynthiainga commented on style.css
> +  }
- [ ] Good job so far, but you still have issues to fix with your design. Your design should stick as much as possible to the figma design. As mentioned by the previous reviewer your popup should be responsive also your design should much to the figma design 🙃 🙃 

Your design

<img width="349" alt="Screen Shot 2023-02-09 at 00 04 00" src="https://user-images.githubusercontent.com/74501523/217652188-a159c049-15fe-45ef-b8c1-7457a290d82d.png">

Figma design

<img width="289" alt="Screen Shot 2023-02-09 at 00 05 03" src="https://user-images.githubusercontent.com/74501523/217652244-4c1c9887-2af6-45a9-ae86-c87ea4490626.png">

2023-02-09 10:37 UTC, mikethreels approved these changes
Hi Oscar, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- linters are passing
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-09 10:42 UTC, merged